### ISSUE TITLE
Cannot list build defintions

### ISSUE THREAD

**Issue by colindembovsky** [MethodsAndPractices/vsteam#198]
Steps to reproduce
------------------

```powershell
Set-VSTeamAccount -Account devops-iaa-dryrun -PersonalAccessToken "mypat"
New-PSDrive -Name azdo -PSProvider SHiPS -Root 'VSTeam#VSTeamAccount'
cd azdo:
cd MyProject\Build Definitions
ls
```

Expected behavior
-----------------

```none
List of build definitions.
```

Actual behavior
---------------

```none
ls : Item 'Build Definitions' may no longer exists. Details: The property 'name' cannot be found on this object.
Verify that the property exists..
At line:1 char:1
+ ls
+ ~~
    + CategoryInfo          : NotSpecified: (SHiPS:String) [Get-ChildItem], Exception
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Get-VSTeamBuildDefinition,Microsoft.PowerShell.Commands.GetChildI
   temCommand
```

Environment data
----------------

OS

- [ ] macOS
- [x] Windows
- [ ] Linux

Server

- [ ] TFS 2017
- [ ] TFS 2018
- [ ] Azure DevOps Server
- [x] Azure DevOps Service

```powershell
> Get-VSTeamAPIVersion
Name                           Value
----                           -----
Release                        5.1-preview
Version                        VSTS
MemberEntitlementManagement    5.1-preview
DistributedTask                5.0-preview
Core                           5.0
Packaging                      5.1-preview
ServiceFabricEndpoint          5.0-preview
VariableGroups                 5.0-preview.1
Build                          5.0
Git                            5.1-preview
ExtensionsManagement           5.1-preview
Graph                          5.1-preview
Tfvc                           5.0
```

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by richardgavel** [comment]
The mention of a YAML vs GUI on https://github.com/DarqueWarrior/vsteam/issues/216 had me research further and I did find it was choking only on GUI based pipelines. Ran the raw REST API and this is what I got, specifically around the embedded "queue" property:

GUI
`
            "queue": {
                "_links": {
                    "self": {
                        "href": "https://dev.azure.com/xxx/_apis/build/Queues/26"
                    }
                },
                "id": 26,
                "url": "https://dev.azure.com/xxx/_apis/build/Queues/26",
                "pool": null
            },
`

YAML
`
            "queue": {
                "_links": {
                    "self": {
                        "href": "https://dev.azure.com/xxx/_apis/build/Queues/235"
                    }
                },
                "id": 235,
                "name": "Self Hosted Docker (Windows 1903)",
                "url": "https://dev.azure.com/xxx/_apis/build/Queues/235",
                "pool": {
                    "id": 26,
                    "name": "Self Hosted Docker (Windows 1903)"
                }
            },
`

**Comment by SebastianSchuetze** [comment]
@richardgavel could you help us in providing a solution for this? code snippets are enough. We can make the PR as well if it is too much effort.

**Comment by SebastianSchuetze** [comment]
@colindembovsky and @richardgavel do this problem still exist for you? I have tested it with both types of build definitions. But I don't have that problem.

Maybe it has been fixed because of another change in the API or with the code. But I cannot find for sure. It would help if you can try to reproduce it again.
Maybe it is a certain configuration that must exist on the build definitions to trigger that exception.

**Comment by DarqueWarrior** [comment]
I just tested today with both builds in the same project and it is working as expected.
