### ISSUE TITLE
Get-VSTeamWIQL

### ISSUE THREAD

**Issue by jhoneill** [MethodsAndPractices/vsteam#314]
- The removal of dynamic parameters #289  somehow missed this one. 
- There was a completer / transformer for query selection in the code drop behind 289 and that got lost in the process.
- The -Team parameter should be optional. (It's described as optional https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/wiql/query%20by%20id?view=azure-devops-rest-5.1) 
-  -Expand fails if the returned items are 'workItemLink' 
-  Range selection for expand can have problems if strict mode is on.

Steps to reproduce
------------------

```powershell
Get-VSTeamWiql -Id 'Assigned to me' -Expand | select -expand workitems | ft
```

Expected behavior
-----------------

```none
Should allow tab completion of the query name, and show work items table
```

Actual behavior
---------------
```none
Prompts for team, No tab expansion. 
```

```powershell
$wiql           = @"
SELECT   [System.Id], [System.WorkItemType], [System.Title], [System.CreatedBy], [System.AssignedTo], [System.State], [System.Tags]
FROM      WorkItemLinks 
WHERE (  [System.Links.LinkType] = 'System.LinkTypes.Hierarchy-Forward')
ORDER BY [System.Id] DESC 
MODE  (   MayContain)
"@    
$w              = Get-VSTeamWiql -Query $wiql -Expand
```

Expected behavior
-----------------

```none
$w contains results of the query. 
```

Actual behavior
---------------
```none
Errors on expand
```
PR in the pipeline for this

**Comment by SebastianSchuetze** [comment]
close this sice it should be fixed with PR #315
