### ISSUE TITLE
Feature Request: Unlist (NuGet) package from feed

### ISSUE THREAD

**Issue by japj** [MethodsAndPractices/vsteam#351]
I would like to unlist all versions of a NuGet package in the AzureDevOps Server feed.

It seems the web ui does this through PATCHing the "listed" to false in 

https://docs.microsoft.com/en-us/rest/api/azure/devops/artifactspackagetypes/nuget/update%20package%20version?view=azure-devops-rest-5.1

However, since there are a lot of versions published for this package (and the web ui only unlists one version at a time), I would like to automate this.

Unfortunately, vsteam does not have support for the (detailed) packages part of the REST API

**Comment by DarqueWarrior** [comment]
To take advantage of this function don't we have to also add a function to list all the current versions of a package as well? Something like this? 

```PowerShell
Get-VSTeamPackageVersion -Name VSTeam | Where-Object version -le 5.0.0 | Update-VSTeamPackageVersion -List $false
```

Or were you seeing this a different way?

**Comment by DarqueWarrior** [comment]
I added Get-VSTeamPackage. From there you can pass -includeAllVersions and get every version of a package. I will also be adding Get-VSTeamPackageVersion to make that a little easier. I think there will be a whole collection of related VSTeamPackage functions coming. Each in a separate PR. I was not going release a version until you see value. Let me know when you see a version you would want pushed.

**Comment by DarqueWarrior** [comment]
I will be working on the final function Update-VSTeamPackageVersion this weekend.

**Comment by DarqueWarrior** [comment]
Functions are in 7.1.0
